language: python

python:
  - 2.7
  - 3.6

sudo: false

branches:
  only:
    - master
    - /^(?:(\d+)\.)?(?:(\d+)\.)?(\*|\d+)$/

cache: pip

notifications:
  email: never
  webhooks: https://galaxy.ansible.com/api/v1/notifications/

install:
  - pip install ansible

script:
- ansible-playbook -i 'localhost,' --syntax-check tests/test.yml
