---
- block:
  - name: Include role variables
    include_vars: ../defaults/trellis-sage-9-compiler.yml

  - name: Clone project files
    git:
      repo: "{{ project_git_repo }}"
      version: "{{ project_version }}"
      dest: "{{ project_build_path }}"
      force: yes
    no_log: false
    connection: local

  - name: Install npm dependencies
    command: yarn
    connection: local
    args:
      chdir: "{{ project_build_site_path }}/web/app/themes/{{ item.name }}"
    with_items: "{{ project.sage_9_compiler }}"

  - name: Install Composer dependencies
    command: composer install --no-ansi --no-dev --no-interaction --no-progress --optimize-autoloader --no-scripts
    args:
      chdir: "{{ deploy_helper.new_release_path }}/web/app/themes/{{ item.name }}"
    with_items: "{{ project.sage_9_compiler }}"

  - name: Compile assets for production
    command: yarn build:production
    connection: local
    args:
      chdir: "{{ project_build_site_path }}/web/app/themes/{{ item.name }}"
    with_items: "{{ project.sage_9_compiler }}"

  - name: Copy production assets
    synchronize:
      src: "{{ project_build_site_path }}/web/app/themes/{{ item.name }}/dist"
      dest: "{{ deploy_helper.new_release_path }}/web/app/themes/{{ item.name }}"
      group: no
      owner: no
      rsync_opts: --chmod=Du=rwx,--chmod=Dg=rx,--chmod=Do=rx,--chmod=Fu=rw,--chmod=Fg=r,--chmod=Fo=r
    with_items: "{{ project.sage_9_compiler }}"

  - name: Clean up theme source files
    file:
      state: absent
      path: "{{ deploy_helper.new_release_path }}/web/app/themes/{{ item.name }}/resources/assets"
    with_items: "{{ project.sage_9_compiler }}"
    when: item.cleanup | default(false)

  when: project.sage_9_compiler is defined
